### ISSUE TITLE
Update the Parse.com URL

### ISSUE THREAD

**Issue by gbrmachado** [dwyl/learn-api-design#26]
The URL for the parse.com API is outdated.
The new one is http://parseplatform.org/

**Comment by nelsonic** [comment]
@gbrmachado if you have time to PR an update, please do! thanks! 🎉

**Comment by gbrmachado** [comment]
Hello @nelsonic I've just created a PR.

**Comment by nelsonic** [comment]
@gbrmachado Thanks for the PR! 🎉
