### ISSUE TITLE
LICENSE.md

### ISSUE THREAD

**Issue by aliceUnhinged613** [dwyl/learn-api-design#41]
git tag -l "v1.8.5*" v1.8.5 v1.8.5-rc0 v1.8.5-rc1 v1.8.5-rc2 v1.8.5-rc3 v1.8.5.1 v1.8.5.2 v1.8.5.3 v1.8.5.4 v1.8.5.5LICENSE.md

**Comment by nelsonic** [comment]
No further action on this issue. closing.
